const dataList = [
    {
        title: 'The Great Lands',
        releasedDate: '2019',
        bookmark: false,
        rating: 'PG',
        id: 1,
        image: '/assets/2.jpg',
        movies: false,
    },
    {
        title: 'The Diary',
        releasedDate: '2019',
        bookmark: false,
        rating: '18+',
        id: 2,
        image: '/assets/2.jpg',
        movies: true,
    },
    {
        title: 'Earth is unlocked',
        releasedDate: '2019',
        bookmark: true,
        rating: 'PG',
        id: 3,
        image: '/assets/2.jpg',
        movies: false,
    },
    {
        title: 'No Land Beyond',
        releasedDate: '2019',
        bookmark: false,
        rating: '18+',
        id: 4,
        movies: true,
        image: '/assets/2.jpg',
    },
    {
        title: 'During the hunt',
        releasedDate: '2019',
        bookmark: true,
        rating: 'PG',
        id: 5,
        image: '/assets/2.jpg',
        movies: false,
    },
    {
        title: 'Autosport the series',
        releasedDate: '2019',
        bookmark: false,
        rating: '18+',
        id: 6,
        image: '/assets/2.jpg',
        movies: true,
    },
    {
        title: 'Same answer',
        releasedDate: '2019',
        bookmark: true,
        rating: 'PG',
        id: 7,
        movies: false,
        image: '/assets/2.jpg',
    },
    {
        title: 'The Great Lands',
        releasedDate: '2019',
        bookmark: false,
        rating: '18+',
        id: 8,
        movies: true,
        image: '/assets/2.jpg',
    },
    {
        title: 'The Great Lands',
        releasedDate: '2019',
        bookmark: false,
        rating: 'PG',
        id: 9,
        image: '/assets/2.jpg',
        movies: false,
    },
    {
        title: 'The Diary',
        releasedDate: '2019',
        bookmark: true,
        movies: true,
        rating: '18+',
        id: 10,
        image: '/assets/2.jpg',
    },
    {
        title: 'Earth is unlocked',
        releasedDate: '2019',
        bookmark: false,
        rating: 'PG',
        movies: false,
        id: 11,
        image: '/assets/2.jpg',
    },
    {
        title: 'No Land Beyond',
        releasedDate: '2019',
        bookmark: false,
        rating: '18+',
        id: 12,
        image: '/assets/2.jpg',
        movies: true,
        
    },
    {
        title: 'During the hunt',
        releasedDate: '2019',
        bookmark: false,
        rating: 'PG',
        id: 13,
        movies: false,
        image: '/assets/2.jpg',
    },
    {
        title: 'Autosport the series',
        releasedDate: '2019',
        bookmark: false,
        rating: '18+',
        id: 14,
        movies: false,
        image: '/assets/2.jpg',
    },
    {
        title: 'Same answer',
        movies: true,
        releasedDate: '2019',
        bookmark: false,
        rating: 'PG',
        id: 15,
        image: '/assets/2.jpg',
    },
    {
        title: 'The Great Lands',
        releasedDate: '2019',
        bookmark: false,
        movies: false,
        rating: '18+',
        id: 16,
        image: '/assets/2.jpg',
    }


]

export default dataList;